name: Unzip
on:
  workflow_dispatch:
    inputs:
      zip_path:
        description: 'Path to zip file'
        required: true
permissions:
  contents: write
jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          unzip -o "${{ github.event.inputs.zip_path }}"
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add .
          git commit -m "Unzip ${{ github.event.inputs.zip_path }}" || echo "nothing to commit"
          git push
